/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "std_types.h"
#include "common_macros.h"
#include "delay.h"

#include "queue.h"
#include "APP.h"

int main(void)
{

	APP_Init();


	while(1)
	{

		if( NUMBER_OF_SAMPLES_TO_SEND_DATA == queue_size() ) /* Send data */
		{
			QUEUE_DATATYPE data[NUMBER_OF_SAMPLES_TO_SEND_DATA];
			for(u16 i=0 ; i<NUMBER_OF_SAMPLES_TO_SEND_DATA ; i++ )
			    dequeue( data+i );
			/*Send data*/
			APP_send_data( data , NUMBER_OF_SAMPLES_TO_SEND_DATA );

		}


	}

}
